import os
import json
import base64
import logging
import uuid
from abc import ABC, abstractmethod
from typing import Any, Dict, Optional
from urllib.parse import urlencode

import httpx

logger = logging.getLogger(__name__)


class SSOClient(ABC):
    @abstractmethod
    def create_organization_and_connection(self, domain: str, entity_name: str) -> Dict[str, Any]:
        """Provision the IdP-side organization/connection for a domain.
        Returns {organization_id, connection_id, admin_portal_url}."""
        ...

    @abstractmethod
    def get_authorization_url(self, connection_id: str, redirect_uri: str, state: str) -> str:
        ...

    @abstractmethod
    def exchange_code_for_profile(self, code: str) -> Dict[str, Any]:
        """Returns {email, connection_id, idp_id}."""
        ...


class WorkOSSSOClient(SSOClient):
    """Real WorkOS SSO integration. WorkOS abstracts SAML/OIDC across every
    major IdP (Okta, Azure AD, Google Workspace, OneLogin, etc.) behind one
    API, which is why it's the fast path for enterprise SSO rather than
    implementing SAML directly."""

    def __init__(self):
        self.api_key = os.getenv("WORKOS_API_KEY")
        self.client_id = os.getenv("WORKOS_CLIENT_ID")
        if not self.api_key or not self.client_id:
            raise ValueError("WORKOS_API_KEY and WORKOS_CLIENT_ID environment variables must be set")

        self.base_url = "https://api.workos.com"
        self.logger = logging.getLogger(__name__)

    def create_organization_and_connection(self, domain: str, entity_name: str) -> Dict[str, Any]:
        try:
            headers = {"Authorization": f"Bearer {self.api_key}"}

            org_resp = httpx.post(
                f"{self.base_url}/organizations",
                headers=headers,
                json={"name": entity_name, "domains": [domain]},
                timeout=30.0,
            )
            org_resp.raise_for_status()
            organization_id = org_resp.json()["id"]

            portal_resp = httpx.post(
                f"{self.base_url}/portal/generate_link",
                headers=headers,
                json={"organization": organization_id, "intent": "sso"},
                timeout=30.0,
            )
            portal_resp.raise_for_status()
            admin_portal_url = portal_resp.json()["link"]

            self.logger.info(f"Created WorkOS organization {organization_id} for domain {domain}")

            return {
                "organization_id": organization_id,
                # The Connection itself is created by the customer's IT admin
                # via the Admin Portal link, so there's no connection_id yet —
                # it's attached once they finish configuring their IdP there.
                "connection_id": None,
                "admin_portal_url": admin_portal_url,
            }
        except Exception as e:
            self.logger.error(f"Failed to create WorkOS organization for {domain}: {e}")
            raise Exception(f"Failed to create WorkOS organization: {str(e)}")

    def get_authorization_url(self, connection_id: str, redirect_uri: str, state: str) -> str:
        params = {
            "client_id": self.client_id,
            "connection": connection_id,
            "redirect_uri": redirect_uri,
            "response_type": "code",
            "state": state,
        }
        return f"{self.base_url}/sso/authorize?{urlencode(params)}"

    def exchange_code_for_profile(self, code: str) -> Dict[str, Any]:
        try:
            response = httpx.post(
                f"{self.base_url}/sso/token",
                data={
                    "client_id": self.client_id,
                    "client_secret": self.api_key,
                    "code": code,
                    "grant_type": "authorization_code",
                },
                timeout=30.0,
            )
            response.raise_for_status()
            data = response.json()
            profile = data.get("profile", {})

            return {
                "email": profile.get("email"),
                "connection_id": profile.get("connection_id"),
                "idp_id": profile.get("idp_id"),
            }
        except Exception as e:
            self.logger.error(f"Failed to exchange WorkOS SSO code: {e}")
            raise Exception(f"Failed to exchange SSO code: {str(e)}")


class MockSSOClient(SSOClient):
    """Mock SSO client for sandbox/demo/testing. There's no real IdP to
    redirect to, so the "authorization code" a caller exchanges is itself a
    base64-encoded profile — generated by `simulate_authorization_code`,
    standing in for what a real IdP round-trip would eventually hand back."""

    def __init__(self):
        self.logger = logging.getLogger(__name__)
        self.logger.info("Using MockSSOClient")

    def create_organization_and_connection(self, domain: str, entity_name: str) -> Dict[str, Any]:
        organization_id = f"org_mock_{uuid.uuid4().hex[:12]}"
        connection_id = f"conn_mock_{uuid.uuid4().hex[:12]}"
        return {
            "organization_id": organization_id,
            "connection_id": connection_id,
            "admin_portal_url": f"https://mock-sso.example.com/portal/{organization_id}",
        }

    def get_authorization_url(self, connection_id: str, redirect_uri: str, state: str) -> str:
        params = {"connection": connection_id, "redirect_uri": redirect_uri, "state": state}
        return f"https://mock-sso.example.com/authorize?{urlencode(params)}"

    def exchange_code_for_profile(self, code: str) -> Dict[str, Any]:
        try:
            decoded = json.loads(base64.urlsafe_b64decode(code.encode()).decode())
        except Exception:
            raise ValueError("Invalid mock SSO authorization code")

        if "email" not in decoded or "connection_id" not in decoded:
            raise ValueError("Malformed mock SSO authorization code")

        return {
            "email": decoded["email"],
            "connection_id": decoded["connection_id"],
            "idp_id": decoded.get("idp_id", f"idp_{decoded['email']}"),
        }

    @staticmethod
    def simulate_authorization_code(email: str, connection_id: str, idp_id: Optional[str] = None) -> str:
        """Test/demo helper standing in for a real IdP login — produces a
        code that exchange_code_for_profile can redeem for this profile."""
        payload = {"email": email, "connection_id": connection_id, "idp_id": idp_id or f"idp_{email}"}
        return base64.urlsafe_b64encode(json.dumps(payload).encode()).decode()


def get_sso_client() -> SSOClient:
    """Factory function to get the appropriate SSO client."""
    use_real = os.getenv("USE_REAL_SSO", "False").lower() in ["true", "1"]

    if use_real:
        return WorkOSSSOClient()
    else:
        return MockSSOClient()
